name: Step 1, Informacion General y Autogestion

on:
  workflow_dispatch:
  push:
    branches:
      - step1-informacion-general

permissions:
  contents: write
  pull-requests: write

jobs:
   on_informacion_general:
    name: On Informacion General

    if: ${{ !github.event.repository.is_template }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check reponse
        run: ./.github/script/check-file.sh
        env:
          FILE: "actividad1.md"
          SEARCH: '([a-zA-Z]*)' 

      - name: Prepare branch, and file
        run: |
          echo "Make sure we are on step 1"
          if [ "$(cat .github/script/STEP)" != 1 ]
          then
            echo "Current step is not 1"
            exit 1
          fi
          echo "Make a branch"
          BRANCH=step2-soporte-devexp
          git checkout -b $BRANCH
          echo "Remove a file"
          git rm actividad1.md
          echo "Make a file"
          touch actividad2.md
          echo -e "- \n 
          - \n" >>actividad2.md
          echo "Make a commit"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit --message="Create activities files"
          echo "Push"
          git push --set-upstream origin $BRANCH
          
          echo "Restore branch"
          git checkout step2-soporte-devexp
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

#The first part of the pattern, [a-zA-Z]+, matches one or more letters.
#The second part of the pattern, (?:_[a-zA-Z]+), matches an undescore if it is followed by one or more letters.
#The * at the end means the second part can be repeated zero or more times.
#The (?: ) is like plain (), but doesn't return the matched group.
   
      # Update README to close <details id=0> and open <details id=1>
      # and set STEP to '2'
      - name: Update to step 2
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: step2-soporte-devexp
